### ISSUE TITLE
1.21.3 support

### ISSUE THREAD

**Issue by ssterling** [CodeF53/Horse-Buff#79]
Mod crashes game on 1.21.3.  Relevant error is as follows:
```
java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1690 failed
	at knot//net.minecraft.class_1299.method_64432(class_1299.java:869)
	at knot//net.minecraft.class_1299.<clinit>(class_1299.java:202)
	at knot//net.minecraft.class_10192.method_64017(class_10192.java:63)
	at knot//net.minecraft.class_1802.method_63920(class_1802.java:528)
	at knot//net.minecraft.class_1802.method_63752(class_1802.java:1508)
	at knot//net.minecraft.class_1802.method_63751(class_1802.java:1527)
	at knot//net.minecraft.class_1802.method_51348(class_1802.java:1551)
	at knot//net.minecraft.class_1802.method_63748(class_1802.java:1527)
	at knot//net.minecraft.class_1802.method_7993(class_1802.java:1523)
	at knot//net.minecraft.class_1802.method_58096(class_1802.java:1508)
	at knot//net.minecraft.class_1802.<clinit>(class_1802.java:528)
	at knot//net.minecraft.class_6089.method_9530(class_6089.java:65)
	at knot//net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1097)
	at knot//net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1093)
	at knot//net.minecraft.class_4970.method_9549(class_4970.java:361)
	at knot//net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1368)
	at knot//net.minecraft.class_4970$class_4971.method_26200(class_4970.java:908)
	at knot//net.minecraft.class_2246.<clinit>(class_2246.java:1311)
	at knot//net.minecraft.class_2358.method_10199(class_2358.java:336)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1690 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 27 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 31 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for horsebuff.mixins.json:Server.AllowRaft from mod horsebuff during activity: [Transform -> Method allowRaft(ZLnet/minecraft/class_1297;)Z -> GETSTATIC -> net/minecraft/class_1690$class_1692::field_40161:Lnet/minecraft/class_1690$class_1692;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 34 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.class_1690$class_1692
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:782)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:745)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 40 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1690$class_1692
	... 44 more
```

**Comment by AllOutJay** [comment]
@ssterling can you update this to be for 1.21.4 support?
